# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2, mbuild
import time
# initialize variables
vuelta = 0

@event.is_press('b')
def is_btn_press():
    global vuelta
    mbot2.servo_set(90,"S3")
    vuelta = 0
    mbuild.smart_camera.set_mode("color", 1)
    mbuild.quad_rgb_sensor.set_led_color("blue", 1)
    cyberpi.reset_rotation('all')
    mbot2.servo_set(90,"all")
    while not vuelta == 4:
      cyberpi.console.print(mbuild.quad_rgb_sensor.get_ground_sta("all", 1))
      if mbuild.quad_rgb_sensor.get_ground_sta("all", 1) > 0:
        mbot2.straight(15)
        mbot2.servo_set(135,"S3")
        while not cyberpi.get_rotation('z') < -89:
          mbot2.drive_power(50, -25)

        mbot2.servo_set(0,"S3")
        mbot2.turn(-13)
        time.sleep(0.3)
        mbot2.servo_set(90,"S3")
        mbot2.straight(5)
        mbot2.EM_stop("ALL")
        time.sleep(0)
        mbot2.servo_set(90,"S3")
        vuelta = vuelta + 1
        cyberpi.reset_rotation('all')

      else:
        mbot2.forward(50)

@event.is_press('middle')
def is_joy_press():
    global vuelta
    # DO SOMETHING
    pass

def correcci_C3_B3n():
    global vuelta
    if cyberpi.get_rotation('z') > 0:
      mbot2.EM_stop("ALL")
      cyberpi.console.println(cyberpi.get_rotation('z'))
      while not cyberpi.get_rotation('z') < 1:
        mbot2.servo_set((mbot2.servo_get("S3") + 1),"S3")
        mbot2.forward(120)
        cyberpi.console.println(cyberpi.get_rotation('z'))

    if cyberpi.get_rotation('z') < 0:
      mbot2.EM_stop("ALL")
      cyberpi.console.println(cyberpi.get_rotation('z'))
      while not cyberpi.get_rotation('z') > -1:
        mbot2.servo_set((mbot2.servo_get("S3") - 1),"S3")
        mbot2.forward(120)
        cyberpi.console.println(cyberpi.get_rotation('z'))

@event.is_press('a')
def is_btn_press1():
    global vuelta
    cyberpi.reset_rotation('all')
    for count2 in range(3):
      for count in range(4):
        mbot2.servo_set(90,"all")
        time.sleep(1)
        mbot2.forward(60, 0.5)
        mbot2.forward(120, 0.5)
        while not mbuild.ranging_sensor.get_distance(3) < 60:
          mbot2.forward(180)

        mbot2.EM_stop("ALL")
        time.sleep(0.1)
        mbot2.servo_set(135,"S3")
        while not cyberpi.get_rotation('z') < -90:
          mbot2.EM_set_speed(40,"EM1")
          cyberpi.console.println(cyberpi.get_rotation('z'))
          cyberpi.console.clear()

        while not cyberpi.get_rotation('z') < 0:
          mbot2.EM_set_speed(-40,"EM1")
          cyberpi.console.println(cyberpi.get_rotation('z'))
          cyberpi.console.clear()

        cyberpi.reset_rotation('all')
        mbot2.EM_stop("ALL")

      mbot2.servo_set(0,"S3")
      mbot2.turn(-15)
      cyberpi.reset_rotation('all')

    mbot2.servo_set(90,"all")
    mbot2.forward(50, 2)

@event.start
def on_start():
    global vuelta
    # DO SOMETHING
    pass

